---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-dra-controller
  labels:
    app: network-dra-controller
spec:
  selector:
    matchLabels:
      app: network-dra-controller
  template:
    metadata:
      labels:
        app: network-dra-controller
    spec:
      serviceAccountName: network-dra-service-account
      hostNetwork: true
      containers:
      - name: network-dra-controller
        image: {{ .Values.registry }}/network-dra-controller:latest
        imagePullPolicy: IfNotPresent
        command:
        - ./network-dra-controller
        args:
        - run
        securityContext:
          privileged: true