---
apiVersion: v1
kind: Pod
metadata:
  name: demo-b
spec:
  containers:
  - name: alpine
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - infinity
  resourceClaims:
  - name: macvlan-eth0-attachment
    source:
      resourceClaimName: macvlan-eth0-attachment
