---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: macvlan-eth0-attach
spec:
  spec:
    resourceClassName: dra.networking
    parametersRef:
      apiGroup: dra.networking/v1alpha1
      kind: NetworkAttachment
      name: macvlan-eth0-attachment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-c
  labels:
    app: demo-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-c
  template:
    metadata:
      labels:
        app: demo-c
    spec:
      serviceAccountName: network-dra-service-account
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - infinity
      resourceClaims:
      - name: macvlan-eth0-attachment
        source:
          resourceClaimTemplateName: macvlan-eth0-attach