---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  name: macvlan-eth0-attach
spec:
  spec:
    devices: 
      requests:
        - name: macvlan-eth0
          deviceClassName: network-interface
      config: 
        - opaque: 
            driver: dra.networking
            parameters:
              apiVersion: dra.networking/v1alpha1
              kind: NetworkAttachment
              metadata:
                name: macvlan-eth0-attach
                namespace: default
              spec:
                name: macvlan-eth0
                interface: net1
    controller: dra.networking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-c
  labels:
    app: demo-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-c
  template:
    metadata:
      labels:
        app: demo-c
    spec:
      serviceAccountName: network-dra-service-account
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - infinity
      resourceClaims:
      - name: macvlan-eth0-attachment
        resourceClaimTemplateName: macvlan-eth0-attach