---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-eth0
  namespace: default
spec:
  config: '{
        "cniVersion":"0.4.0",
        "type":"macvlan",
        "master":"eth0",
        "mode":"bridge",
        "ipam": {
          "type": "host-local",
          "ranges": [
          	[
            	{
                "subnet": "10.10.1.0/24"
              }
            ]
          ]
        }
    }'
---
apiVersion: dra.networking/v1alpha1
kind: NetworkAttachment
metadata:
  name: macvlan-eth0-attachment
spec:
  name: macvlan-eth0
  interface: net1
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  name: macvlan-eth0-attachment
spec:
  resourceClassName: dra.networking
  parametersRef:
    apiGroup: k8s.cni.cncf.io
    kind: NetworkAttachmentDefinition
    name: macvlan-eth0-attachment
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-a
spec:
  containers:
  - name: alpine
    image: alpine
    command:
    - sleep
    - infinity
    resources:
      claims:
      - name: macvlan-eth0-attachment
  resourceClaims:
  - name: macvlan-eth0-attachment
    source:
      resourceClaimName: macvlan-eth0-attachment
