/*
Copyright (c) 2024

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/LionelJouin/network-dra/api/dra.networking/v1alpha1"
	scheme "github.com/LionelJouin/network-dra/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkAttachmentsGetter has a method to return a NetworkAttachmentInterface.
// A group's client should implement this interface.
type NetworkAttachmentsGetter interface {
	NetworkAttachments(namespace string) NetworkAttachmentInterface
}

// NetworkAttachmentInterface has methods to work with NetworkAttachment resources.
type NetworkAttachmentInterface interface {
	Create(ctx context.Context, networkAttachment *v1alpha1.NetworkAttachment, opts v1.CreateOptions) (*v1alpha1.NetworkAttachment, error)
	Update(ctx context.Context, networkAttachment *v1alpha1.NetworkAttachment, opts v1.UpdateOptions) (*v1alpha1.NetworkAttachment, error)
	UpdateStatus(ctx context.Context, networkAttachment *v1alpha1.NetworkAttachment, opts v1.UpdateOptions) (*v1alpha1.NetworkAttachment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NetworkAttachment, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NetworkAttachmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkAttachment, err error)
	NetworkAttachmentExpansion
}

// networkAttachments implements NetworkAttachmentInterface
type networkAttachments struct {
	client rest.Interface
	ns     string
}

// newNetworkAttachments returns a NetworkAttachments
func newNetworkAttachments(c *DraV1alpha1Client, namespace string) *networkAttachments {
	return &networkAttachments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkAttachment, and returns the corresponding networkAttachment object, and an error if there is any.
func (c *networkAttachments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkAttachment, err error) {
	result = &v1alpha1.NetworkAttachment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkattachments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkAttachments that match those selectors.
func (c *networkAttachments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkAttachmentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkAttachmentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkattachments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkAttachments.
func (c *networkAttachments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networkattachments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkAttachment and creates it.  Returns the server's representation of the networkAttachment, and an error, if there is any.
func (c *networkAttachments) Create(ctx context.Context, networkAttachment *v1alpha1.NetworkAttachment, opts v1.CreateOptions) (result *v1alpha1.NetworkAttachment, err error) {
	result = &v1alpha1.NetworkAttachment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networkattachments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkAttachment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkAttachment and updates it. Returns the server's representation of the networkAttachment, and an error, if there is any.
func (c *networkAttachments) Update(ctx context.Context, networkAttachment *v1alpha1.NetworkAttachment, opts v1.UpdateOptions) (result *v1alpha1.NetworkAttachment, err error) {
	result = &v1alpha1.NetworkAttachment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkattachments").
		Name(networkAttachment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkAttachment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *networkAttachments) UpdateStatus(ctx context.Context, networkAttachment *v1alpha1.NetworkAttachment, opts v1.UpdateOptions) (result *v1alpha1.NetworkAttachment, err error) {
	result = &v1alpha1.NetworkAttachment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkattachments").
		Name(networkAttachment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkAttachment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkAttachment and deletes it. Returns an error if one occurs.
func (c *networkAttachments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkattachments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkAttachments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkattachments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkAttachment.
func (c *networkAttachments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkAttachment, err error) {
	result = &v1alpha1.NetworkAttachment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networkattachments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
